DATA_ROOT: '/dataset/'
LOGS_ROOT: '../logs/'


MODEL:
  # architecture
  backbone: 'resnet50'
  pooling: 'gem'
  embed_feat: 0
  dropout: 0.

  dsbn: True

  sync_bn: True
  samples_per_bn: 16

  mean_net: False
  alpha: 0.999

  # pretraining
  imagenet_pretrained: False
  source_pretrained: '../logs/source_pretrain/market1501/checkpoint.pth'


DATA:
  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

  TRAIN:
    # augmentation
    is_autoaug: False

    is_flip: False
    flip_prob: 0.0

    is_pad: False
    pad_size: 10

    is_blur: False
    blur_prob: 0.0

    is_erase: False
    erase_prob: 0.0

    # dual augmentation for MMT
    is_mutual_transform: False
    mutual_times: 2


TRAIN:
  seed: 1
  deterministic: True
  # mixed precision training for PyTorch>=1.6
  amp: False
  
  datasets: {"": ""}
  
  LOADER:
    samples_per_gpu: 16


TEST:

  # datasets
  GALLERY:
    dataset: "market1501"
    corruption: null
    
  QUERY:
    dataset: "market1501"
    corruption: ["gaussian_blur", 43]

  # data loader
  LOADER:
    samples_per_gpu: 16
    workers_per_gpu: 2

